// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2zJOCG4vHWZy5HbqYVjIZLvAxC8qq2jQ',
    appId: '1:20680886099:web:d2ec84b13d8a8584c503a6',
    messagingSenderId: '20680886099',
    projectId: 'cinediary-af776',
    authDomain: 'cinediary-af776.firebaseapp.com',
    storageBucket: 'cinediary-af776.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZE2WUeakXyIy1eIK7AQK2_zJ0hmIDxbA',
    appId: '1:20680886099:android:3edd5e27f732bbabc503a6',
    messagingSenderId: '20680886099',
    projectId: 'cinediary-af776',
    storageBucket: 'cinediary-af776.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6-DPBEDuuQq-c-v3H7QeCDtw5TlQ1qk0',
    appId: '1:20680886099:ios:47e7ef200852fc07c503a6',
    messagingSenderId: '20680886099',
    projectId: 'cinediary-af776',
    storageBucket: 'cinediary-af776.firebasestorage.app',
    iosBundleId: 'com.example.proj1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6-DPBEDuuQq-c-v3H7QeCDtw5TlQ1qk0',
    appId: '1:20680886099:ios:47e7ef200852fc07c503a6',
    messagingSenderId: '20680886099',
    projectId: 'cinediary-af776',
    storageBucket: 'cinediary-af776.firebasestorage.app',
    iosBundleId: 'com.example.proj1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2zJOCG4vHWZy5HbqYVjIZLvAxC8qq2jQ',
    appId: '1:20680886099:web:7b751e228587ef4ec503a6',
    messagingSenderId: '20680886099',
    projectId: 'cinediary-af776',
    authDomain: 'cinediary-af776.firebaseapp.com',
    storageBucket: 'cinediary-af776.firebasestorage.app',
  );
}
